### ISSUE TITLE
I want to maximize this function, but the code can't find the optimal solution

### ISSUE THREAD

**Issue by longbiscuit** [alpsayin/genetic-algorithm-matlab#2]
I replaced the target function in EvaluateIndividual.m file：
`    x1=x(1);
    x2=x(2);
    fitnessValue =- (-40*x1*cos(x2)-35*x2*sin(x1)+15*x1^2-sin(x1)*20+12*x2^2-25*x1*x2*sin(x1*x2^2*cos(x1+x2)));`

at the same time， I changed the genetic algorithm Settings parameters in FunctionOptimization.m file：
`
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
%   Alp Sayin - alp_sayin[at]ieee[dot]org
%   Matlab Genetic Algorithm
%   Spring 2012
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% CLEAN-UP
clear;close all;clc;
tic

%% PARAMETERS
populationSize = 1000 ;
numberOfGenes = 40;
crossoverProbability = 0.8 ;
mutationProbability = 0.0625;
tournamentSelectionParameter = 0.5;
variableRange = 50.0;
numberOfGenerations = 5000;
numberOfVariables = 2;
tournamentSize = 10;
numberOfReplications = 2;
verbose = true;
draw_plots = true;
% UNLESS THE FITNESS FUNCTION IS REALLY DIFFICULT TO COMPUTE, IT'S FASTER
% NOT TO USE PARALLEL COMPUTATION
runparallel = false; 
`
The maximum value should be 735.484897639184，The corresponding two parameter values should be ：
x1: -20.3956600843891
x2: -22.0150462042061

but this matlab code can't find the best solution：
![image](https://user-images.githubusercontent.com/21994802/105573161-8e5eff00-5d96-11eb-992c-3e6a6a7b7b0b.png)

Maximum Fitness: 7.286375e+02
Best Solution: 17.1875
Best Solution: -18.843
时间已过 120.739511 秒。

Is there a way you can improve the search capability of your genetic algorithm ？

**Comment by alpsayin** [comment]
Hi @longbiscuit thanks for trying this out. The problem is not with the genetic algorithm nor its implementation nor the parameters but it's to do with the nature of your optimisation goal (i.e. your cost function). Genetic algorithm assumes that there are certain trends that will yield a "better" result _(in fact, when you're the one using genetic algorithm you're the one making the assumption)_. Your function's maximum values are however distributed pretty randomly (figure 1). But even then, the genetic algorithm does a pretty good job of finding those trends (_genes if you like_) and still returns a very good result. With your settings, by 500th generated I already had 731 (see figure.2).
 
![image](https://user-images.githubusercontent.com/1707616/110461280-47c42a80-80e0-11eb-9440-1b86e7f7f52b.png)
Figure.1

![image](https://user-images.githubusercontent.com/1707616/110461588-b0aba280-80e0-11eb-9e94-b1a9c29dc289.png)
Figure.2

But I think we need to take a step back. Let me explain what a genetic algorithm is and what it's not. It's a heuristic search algorithm, which means it trades-off computation need for the "bestness" of the result. Heuristic algorithms' goal is to return a "good" result, not the best. Therefore it would be foolish to run a heuristic algorithm and expect the best. In fact, often times, trying to reach the best result by using a heuristic algorithm will be more _(cpu)_ costly due to randomness mixed into _(most of_) their nature. You may get lucky once or twice but that doesnt mean they always perform. You must have already noticed that my results are better than yours, and that your execution did not perform as well as mine.

If you want the "best" result, especially with a function like this one where bestness seems random _(and honestly it also seems dependent on quantisation resolution, try and see what happens if you use 20 and 80 genes...)_ and less based on your variables, you have no choice but to perform an exhaustive search. 
However, you can always try to make the optimiser's goal easier. Some standard methods involve 
1. Normalising the cost function
2. Deciding if you want to take 1/x or -x of your cost function to create a fitness function. Of course you gotta be careful with the signedness of your original cost function.
3. Passing your cost function through another function which is also always decreasing _(or always increasing in the case of fitness)_. Perhaps functions like Sigmoid or ReLU that AI people use may be applicable here too.

Edit: copying in the final results of my first and only run of this with your parameters. Run on Windows MacbookPro8.3.
```
Maximum Fitness: 7.349933e+02
Best Solution: -2.041976e+01
Best Solution: -2.200429e+01
Elapsed time is 490.975994 seconds.
```
